<?xml version="1.0" encoding="utf-8"?><Database Name="QL_THUVIEN" Class="DatabaseDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Table Name="dbo.Audit_UserActions" Member="Audit_UserActions">
    <Type Name="Audit_UserAction">
      <Column Name="AuditId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="AdminUser" Type="System.String" DbType="NVarChar(128)" CanBeNull="true" />
      <Column Name="TargetUser" Type="System.String" DbType="NVarChar(128)" CanBeNull="true" />
      <Column Name="ActionType" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="ObjectName" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="Details" Type="System.String" DbType="NVarChar(400)" CanBeNull="true" />
      <Column Name="ActionTime" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Success" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.THELOAI" Member="THELOAIs">
    <Type Name="THELOAI">
      <Column Name="maTL" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="tenTL" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Association Name="THELOAI_SACH" Member="SACHes" ThisKey="maTL" OtherKey="maTL" Type="SACH" />
    </Type>
  </Table>
  <Table Name="dbo.CALAMVIEC" Member="CALAMVIECs">
    <Type Name="CALAMVIEC">
      <Column Name="maCA" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="buoi" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
      <Column Name="thoiGianBD" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="thoiGianKT" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Association Name="CALAMVIEC_PHANCONG" Member="PHANCONGs" ThisKey="maCA" OtherKey="maCA" Type="PHANCONG" />
    </Type>
  </Table>
  <Table Name="dbo.CTPHIEUMUON" Member="CTPHIEUMUONs">
    <Type Name="CTPHIEUMUON">
      <Column Name="maPMUON" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="maSach" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="soLuong" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="PHIEUMUON_CTPHIEUMUON" Member="PHIEUMUON" ThisKey="maPMUON" OtherKey="maPMUON" Type="PHIEUMUON" IsForeignKey="true" />
      <Association Name="SACH_CTPHIEUMUON" Member="SACH" ThisKey="maSach" OtherKey="maSach" Type="SACH" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.DOCGIA" Member="DOCGIAs">
    <Type Name="DOCGIA">
      <Column Name="maDocGia" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="hoTenDG" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="gioiTinh" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="ngaySinh" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="diaChi" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="sdt" Type="System.String" DbType="NChar(13)" CanBeNull="true" />
      <Column Name="email" Type="System.String" DbType="NChar(50)" CanBeNull="true" />
      <Association Name="DOCGIA_PHIEUMUON" Member="PHIEUMUONs" ThisKey="maDocGia" OtherKey="maDocGia" Type="PHIEUMUON" />
    </Type>
  </Table>
  <Table Name="dbo.LOG_MUONTRA" Member="LOG_MUONTRAs">
    <Type Name="LOG_MUONTRA">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="hanhDong" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="maSach" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="maDocGia" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="soLuong" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="thoiGianThucHien" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.NHANVIEN" Member="NHANVIENs">
    <Type Name="NHANVIEN">
      <Column Name="maNV" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="hoTenNV" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="gioiTinh" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="ngaySinh" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="chucVu" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="sdt" Type="System.String" DbType="NChar(13)" CanBeNull="true" />
      <Column Name="email" Type="System.String" DbType="NChar(50)" CanBeNull="true" />
      <Column Name="DBUserName" Type="System.String" DbType="NVarChar(128)" CanBeNull="true" />
      <Association Name="NHANVIEN_PHANCONG" Member="PHANCONGs" ThisKey="maNV" OtherKey="maNV" Type="PHANCONG" />
      <Association Name="NHANVIEN_PHIEUMUON" Member="PHIEUMUONs" ThisKey="maNV" OtherKey="maNV" Type="PHIEUMUON" />
    </Type>
  </Table>
  <Table Name="dbo.NXB" Member="NXBs">
    <Type Name="NXB">
      <Column Name="maNXB" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="tenNXB" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="diaChi" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Association Name="NXB_SACH" Member="SACHes" ThisKey="maNXB" OtherKey="maNXB" Type="SACH" />
    </Type>
  </Table>
  <Table Name="dbo.PHANCONG" Member="PHANCONGs">
    <Type Name="PHANCONG">
      <Column Name="maCA" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="maNV" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="ngayPhanCong" Type="System.DateTime" DbType="Date NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Association Name="CALAMVIEC_PHANCONG" Member="CALAMVIEC" ThisKey="maCA" OtherKey="maCA" Type="CALAMVIEC" IsForeignKey="true" />
      <Association Name="NHANVIEN_PHANCONG" Member="NHANVIEN" ThisKey="maNV" OtherKey="maNV" Type="NHANVIEN" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.PHIEUMUON" Member="PHIEUMUONs">
    <Type Name="PHIEUMUON">
      <Column Name="maPMUON" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ngayMuon" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="ngayTra" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="daTra" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="maDocGia" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="maNV" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="PHIEUMUON_CTPHIEUMUON" Member="CTPHIEUMUONs" ThisKey="maPMUON" OtherKey="maPMUON" Type="CTPHIEUMUON" />
      <Association Name="DOCGIA_PHIEUMUON" Member="DOCGIA" ThisKey="maDocGia" OtherKey="maDocGia" Type="DOCGIA" IsForeignKey="true" />
      <Association Name="NHANVIEN_PHIEUMUON" Member="NHANVIEN" ThisKey="maNV" OtherKey="maNV" Type="NHANVIEN" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.SACH" Member="SACHes">
    <Type Name="SACH">
      <Column Name="maSach" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="tenSach" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="namXuatBan" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="slSach" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="SlConLai" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="maNXB" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="maTL" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="maTG" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="anhBia" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="mota" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Association Name="SACH_CTPHIEUMUON" Member="CTPHIEUMUONs" ThisKey="maSach" OtherKey="maSach" Type="CTPHIEUMUON" />
      <Association Name="NXB_SACH" Member="NXB" ThisKey="maNXB" OtherKey="maNXB" Type="NXB" IsForeignKey="true" />
      <Association Name="THELOAI_SACH" Member="THELOAI" ThisKey="maTL" OtherKey="maTL" Type="THELOAI" IsForeignKey="true" />
      <Association Name="TACGIA_SACH" Member="TACGIA" ThisKey="maTG" OtherKey="maTG" Type="TACGIA" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.TACGIA" Member="TACGIAs">
    <Type Name="TACGIA">
      <Column Name="maTG" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="hoTenTG" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="ngaySinh" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="gioiTinh" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Association Name="TACGIA_SACH" Member="SACHes" ThisKey="maTG" OtherKey="maTG" Type="SACH" />
    </Type>
  </Table>
</Database>