#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QL_ThuVien.Models
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="QL_THUVIEN")]
	public partial class DatabaseDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertAudit_UserAction(Audit_UserAction instance);
    partial void UpdateAudit_UserAction(Audit_UserAction instance);
    partial void DeleteAudit_UserAction(Audit_UserAction instance);
    partial void InsertTHELOAI(THELOAI instance);
    partial void UpdateTHELOAI(THELOAI instance);
    partial void DeleteTHELOAI(THELOAI instance);
    partial void InsertCALAMVIEC(CALAMVIEC instance);
    partial void UpdateCALAMVIEC(CALAMVIEC instance);
    partial void DeleteCALAMVIEC(CALAMVIEC instance);
    partial void InsertCTPHIEUMUON(CTPHIEUMUON instance);
    partial void UpdateCTPHIEUMUON(CTPHIEUMUON instance);
    partial void DeleteCTPHIEUMUON(CTPHIEUMUON instance);
    partial void InsertDOCGIA(DOCGIA instance);
    partial void UpdateDOCGIA(DOCGIA instance);
    partial void DeleteDOCGIA(DOCGIA instance);
    partial void InsertLOG_MUONTRA(LOG_MUONTRA instance);
    partial void UpdateLOG_MUONTRA(LOG_MUONTRA instance);
    partial void DeleteLOG_MUONTRA(LOG_MUONTRA instance);
    partial void InsertNHANVIEN(NHANVIEN instance);
    partial void UpdateNHANVIEN(NHANVIEN instance);
    partial void DeleteNHANVIEN(NHANVIEN instance);
    partial void InsertNXB(NXB instance);
    partial void UpdateNXB(NXB instance);
    partial void DeleteNXB(NXB instance);
    partial void InsertPHANCONG(PHANCONG instance);
    partial void UpdatePHANCONG(PHANCONG instance);
    partial void DeletePHANCONG(PHANCONG instance);
    partial void InsertPHIEUMUON(PHIEUMUON instance);
    partial void UpdatePHIEUMUON(PHIEUMUON instance);
    partial void DeletePHIEUMUON(PHIEUMUON instance);
    partial void InsertSACH(SACH instance);
    partial void UpdateSACH(SACH instance);
    partial void DeleteSACH(SACH instance);
    partial void InsertTACGIA(TACGIA instance);
    partial void UpdateTACGIA(TACGIA instance);
    partial void DeleteTACGIA(TACGIA instance);
    #endregion
		
		public DatabaseDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DatabaseDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DatabaseDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DatabaseDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Audit_UserAction> Audit_UserActions
		{
			get
			{
				return this.GetTable<Audit_UserAction>();
			}
		}
		
		public System.Data.Linq.Table<THELOAI> THELOAIs
		{
			get
			{
				return this.GetTable<THELOAI>();
			}
		}
		
		public System.Data.Linq.Table<CALAMVIEC> CALAMVIECs
		{
			get
			{
				return this.GetTable<CALAMVIEC>();
			}
		}
		
		public System.Data.Linq.Table<CTPHIEUMUON> CTPHIEUMUONs
		{
			get
			{
				return this.GetTable<CTPHIEUMUON>();
			}
		}
		
		public System.Data.Linq.Table<DOCGIA> DOCGIAs
		{
			get
			{
				return this.GetTable<DOCGIA>();
			}
		}
		
		public System.Data.Linq.Table<LOG_MUONTRA> LOG_MUONTRAs
		{
			get
			{
				return this.GetTable<LOG_MUONTRA>();
			}
		}
		
		public System.Data.Linq.Table<NHANVIEN> NHANVIENs
		{
			get
			{
				return this.GetTable<NHANVIEN>();
			}
		}
		
		public System.Data.Linq.Table<NXB> NXBs
		{
			get
			{
				return this.GetTable<NXB>();
			}
		}
		
		public System.Data.Linq.Table<PHANCONG> PHANCONGs
		{
			get
			{
				return this.GetTable<PHANCONG>();
			}
		}
		
		public System.Data.Linq.Table<PHIEUMUON> PHIEUMUONs
		{
			get
			{
				return this.GetTable<PHIEUMUON>();
			}
		}
		
		public System.Data.Linq.Table<SACH> SACHes
		{
			get
			{
				return this.GetTable<SACH>();
			}
		}
		
		public System.Data.Linq.Table<TACGIA> TACGIAs
		{
			get
			{
				return this.GetTable<TACGIA>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Audit_UserActions")]
	public partial class Audit_UserAction : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _AuditId;
		
		private string _AdminUser;
		
		private string _TargetUser;
		
		private string _ActionType;
		
		private string _ObjectName;
		
		private string _Details;
		
		private System.Nullable<System.DateTime> _ActionTime;
		
		private System.Nullable<bool> _Success;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnAuditIdChanging(int value);
    partial void OnAuditIdChanged();
    partial void OnAdminUserChanging(string value);
    partial void OnAdminUserChanged();
    partial void OnTargetUserChanging(string value);
    partial void OnTargetUserChanged();
    partial void OnActionTypeChanging(string value);
    partial void OnActionTypeChanged();
    partial void OnObjectNameChanging(string value);
    partial void OnObjectNameChanged();
    partial void OnDetailsChanging(string value);
    partial void OnDetailsChanged();
    partial void OnActionTimeChanging(System.Nullable<System.DateTime> value);
    partial void OnActionTimeChanged();
    partial void OnSuccessChanging(System.Nullable<bool> value);
    partial void OnSuccessChanged();
    #endregion
		
		public Audit_UserAction()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AuditId", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int AuditId
		{
			get
			{
				return this._AuditId;
			}
			set
			{
				if ((this._AuditId != value))
				{
					this.OnAuditIdChanging(value);
					this.SendPropertyChanging();
					this._AuditId = value;
					this.SendPropertyChanged("AuditId");
					this.OnAuditIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AdminUser", DbType="NVarChar(128)")]
		public string AdminUser
		{
			get
			{
				return this._AdminUser;
			}
			set
			{
				if ((this._AdminUser != value))
				{
					this.OnAdminUserChanging(value);
					this.SendPropertyChanging();
					this._AdminUser = value;
					this.SendPropertyChanged("AdminUser");
					this.OnAdminUserChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TargetUser", DbType="NVarChar(128)")]
		public string TargetUser
		{
			get
			{
				return this._TargetUser;
			}
			set
			{
				if ((this._TargetUser != value))
				{
					this.OnTargetUserChanging(value);
					this.SendPropertyChanging();
					this._TargetUser = value;
					this.SendPropertyChanged("TargetUser");
					this.OnTargetUserChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ActionType", DbType="NVarChar(50)")]
		public string ActionType
		{
			get
			{
				return this._ActionType;
			}
			set
			{
				if ((this._ActionType != value))
				{
					this.OnActionTypeChanging(value);
					this.SendPropertyChanging();
					this._ActionType = value;
					this.SendPropertyChanged("ActionType");
					this.OnActionTypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ObjectName", DbType="NVarChar(200)")]
		public string ObjectName
		{
			get
			{
				return this._ObjectName;
			}
			set
			{
				if ((this._ObjectName != value))
				{
					this.OnObjectNameChanging(value);
					this.SendPropertyChanging();
					this._ObjectName = value;
					this.SendPropertyChanged("ObjectName");
					this.OnObjectNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Details", DbType="NVarChar(400)")]
		public string Details
		{
			get
			{
				return this._Details;
			}
			set
			{
				if ((this._Details != value))
				{
					this.OnDetailsChanging(value);
					this.SendPropertyChanging();
					this._Details = value;
					this.SendPropertyChanged("Details");
					this.OnDetailsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ActionTime", DbType="DateTime")]
		public System.Nullable<System.DateTime> ActionTime
		{
			get
			{
				return this._ActionTime;
			}
			set
			{
				if ((this._ActionTime != value))
				{
					this.OnActionTimeChanging(value);
					this.SendPropertyChanging();
					this._ActionTime = value;
					this.SendPropertyChanged("ActionTime");
					this.OnActionTimeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Success", DbType="Bit")]
		public System.Nullable<bool> Success
		{
			get
			{
				return this._Success;
			}
			set
			{
				if ((this._Success != value))
				{
					this.OnSuccessChanging(value);
					this.SendPropertyChanging();
					this._Success = value;
					this.SendPropertyChanged("Success");
					this.OnSuccessChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.THELOAI")]
	public partial class THELOAI : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _maTL;
		
		private string _tenTL;
		
		private EntitySet<SACH> _SACHes;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnmaTLChanging(int value);
    partial void OnmaTLChanged();
    partial void OntenTLChanging(string value);
    partial void OntenTLChanged();
    #endregion
		
		public THELOAI()
		{
			this._SACHes = new EntitySet<SACH>(new Action<SACH>(this.attach_SACHes), new Action<SACH>(this.detach_SACHes));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maTL", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int maTL
		{
			get
			{
				return this._maTL;
			}
			set
			{
				if ((this._maTL != value))
				{
					this.OnmaTLChanging(value);
					this.SendPropertyChanging();
					this._maTL = value;
					this.SendPropertyChanged("maTL");
					this.OnmaTLChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tenTL", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string tenTL
		{
			get
			{
				return this._tenTL;
			}
			set
			{
				if ((this._tenTL != value))
				{
					this.OntenTLChanging(value);
					this.SendPropertyChanging();
					this._tenTL = value;
					this.SendPropertyChanged("tenTL");
					this.OntenTLChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="THELOAI_SACH", Storage="_SACHes", ThisKey="maTL", OtherKey="maTL")]
		public EntitySet<SACH> SACHes
		{
			get
			{
				return this._SACHes;
			}
			set
			{
				this._SACHes.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_SACHes(SACH entity)
		{
			this.SendPropertyChanging();
			entity.THELOAI = this;
		}
		
		private void detach_SACHes(SACH entity)
		{
			this.SendPropertyChanging();
			entity.THELOAI = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.CALAMVIEC")]
	public partial class CALAMVIEC : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _maCA;
		
		private string _buoi;
		
		private System.Nullable<System.DateTime> _thoiGianBD;
		
		private System.Nullable<System.DateTime> _thoiGianKT;
		
		private EntitySet<PHANCONG> _PHANCONGs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnmaCAChanging(int value);
    partial void OnmaCAChanged();
    partial void OnbuoiChanging(string value);
    partial void OnbuoiChanged();
    partial void OnthoiGianBDChanging(System.Nullable<System.DateTime> value);
    partial void OnthoiGianBDChanged();
    partial void OnthoiGianKTChanging(System.Nullable<System.DateTime> value);
    partial void OnthoiGianKTChanged();
    #endregion
		
		public CALAMVIEC()
		{
			this._PHANCONGs = new EntitySet<PHANCONG>(new Action<PHANCONG>(this.attach_PHANCONGs), new Action<PHANCONG>(this.detach_PHANCONGs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maCA", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int maCA
		{
			get
			{
				return this._maCA;
			}
			set
			{
				if ((this._maCA != value))
				{
					this.OnmaCAChanging(value);
					this.SendPropertyChanging();
					this._maCA = value;
					this.SendPropertyChanged("maCA");
					this.OnmaCAChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_buoi", DbType="NVarChar(10)")]
		public string buoi
		{
			get
			{
				return this._buoi;
			}
			set
			{
				if ((this._buoi != value))
				{
					this.OnbuoiChanging(value);
					this.SendPropertyChanging();
					this._buoi = value;
					this.SendPropertyChanged("buoi");
					this.OnbuoiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_thoiGianBD", DbType="Date")]
		public System.Nullable<System.DateTime> thoiGianBD
		{
			get
			{
				return this._thoiGianBD;
			}
			set
			{
				if ((this._thoiGianBD != value))
				{
					this.OnthoiGianBDChanging(value);
					this.SendPropertyChanging();
					this._thoiGianBD = value;
					this.SendPropertyChanged("thoiGianBD");
					this.OnthoiGianBDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_thoiGianKT", DbType="Date")]
		public System.Nullable<System.DateTime> thoiGianKT
		{
			get
			{
				return this._thoiGianKT;
			}
			set
			{
				if ((this._thoiGianKT != value))
				{
					this.OnthoiGianKTChanging(value);
					this.SendPropertyChanging();
					this._thoiGianKT = value;
					this.SendPropertyChanged("thoiGianKT");
					this.OnthoiGianKTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="CALAMVIEC_PHANCONG", Storage="_PHANCONGs", ThisKey="maCA", OtherKey="maCA")]
		public EntitySet<PHANCONG> PHANCONGs
		{
			get
			{
				return this._PHANCONGs;
			}
			set
			{
				this._PHANCONGs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_PHANCONGs(PHANCONG entity)
		{
			this.SendPropertyChanging();
			entity.CALAMVIEC = this;
		}
		
		private void detach_PHANCONGs(PHANCONG entity)
		{
			this.SendPropertyChanging();
			entity.CALAMVIEC = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.CTPHIEUMUON")]
	public partial class CTPHIEUMUON : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _maPMUON;
		
		private int _maSach;
		
		private int _soLuong;
		
		private EntityRef<PHIEUMUON> _PHIEUMUON;
		
		private EntityRef<SACH> _SACH;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnmaPMUONChanging(int value);
    partial void OnmaPMUONChanged();
    partial void OnmaSachChanging(int value);
    partial void OnmaSachChanged();
    partial void OnsoLuongChanging(int value);
    partial void OnsoLuongChanged();
    #endregion
		
		public CTPHIEUMUON()
		{
			this._PHIEUMUON = default(EntityRef<PHIEUMUON>);
			this._SACH = default(EntityRef<SACH>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maPMUON", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int maPMUON
		{
			get
			{
				return this._maPMUON;
			}
			set
			{
				if ((this._maPMUON != value))
				{
					if (this._PHIEUMUON.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnmaPMUONChanging(value);
					this.SendPropertyChanging();
					this._maPMUON = value;
					this.SendPropertyChanged("maPMUON");
					this.OnmaPMUONChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maSach", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int maSach
		{
			get
			{
				return this._maSach;
			}
			set
			{
				if ((this._maSach != value))
				{
					if (this._SACH.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnmaSachChanging(value);
					this.SendPropertyChanging();
					this._maSach = value;
					this.SendPropertyChanged("maSach");
					this.OnmaSachChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_soLuong", DbType="Int NOT NULL")]
		public int soLuong
		{
			get
			{
				return this._soLuong;
			}
			set
			{
				if ((this._soLuong != value))
				{
					this.OnsoLuongChanging(value);
					this.SendPropertyChanging();
					this._soLuong = value;
					this.SendPropertyChanged("soLuong");
					this.OnsoLuongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="PHIEUMUON_CTPHIEUMUON", Storage="_PHIEUMUON", ThisKey="maPMUON", OtherKey="maPMUON", IsForeignKey=true)]
		public PHIEUMUON PHIEUMUON
		{
			get
			{
				return this._PHIEUMUON.Entity;
			}
			set
			{
				PHIEUMUON previousValue = this._PHIEUMUON.Entity;
				if (((previousValue != value) 
							|| (this._PHIEUMUON.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._PHIEUMUON.Entity = null;
						previousValue.CTPHIEUMUONs.Remove(this);
					}
					this._PHIEUMUON.Entity = value;
					if ((value != null))
					{
						value.CTPHIEUMUONs.Add(this);
						this._maPMUON = value.maPMUON;
					}
					else
					{
						this._maPMUON = default(int);
					}
					this.SendPropertyChanged("PHIEUMUON");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="SACH_CTPHIEUMUON", Storage="_SACH", ThisKey="maSach", OtherKey="maSach", IsForeignKey=true)]
		public SACH SACH
		{
			get
			{
				return this._SACH.Entity;
			}
			set
			{
				SACH previousValue = this._SACH.Entity;
				if (((previousValue != value) 
							|| (this._SACH.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._SACH.Entity = null;
						previousValue.CTPHIEUMUONs.Remove(this);
					}
					this._SACH.Entity = value;
					if ((value != null))
					{
						value.CTPHIEUMUONs.Add(this);
						this._maSach = value.maSach;
					}
					else
					{
						this._maSach = default(int);
					}
					this.SendPropertyChanged("SACH");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.DOCGIA")]
	public partial class DOCGIA : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _maDocGia;
		
		private string _hoTenDG;
		
		private System.Nullable<bool> _gioiTinh;
		
		private System.Nullable<System.DateTime> _ngaySinh;
		
		private string _diaChi;
		
		private string _sdt;
		
		private string _email;
		
		private EntitySet<PHIEUMUON> _PHIEUMUONs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnmaDocGiaChanging(int value);
    partial void OnmaDocGiaChanged();
    partial void OnhoTenDGChanging(string value);
    partial void OnhoTenDGChanged();
    partial void OngioiTinhChanging(System.Nullable<bool> value);
    partial void OngioiTinhChanged();
    partial void OnngaySinhChanging(System.Nullable<System.DateTime> value);
    partial void OnngaySinhChanged();
    partial void OndiaChiChanging(string value);
    partial void OndiaChiChanged();
    partial void OnsdtChanging(string value);
    partial void OnsdtChanged();
    partial void OnemailChanging(string value);
    partial void OnemailChanged();
    #endregion
		
		public DOCGIA()
		{
			this._PHIEUMUONs = new EntitySet<PHIEUMUON>(new Action<PHIEUMUON>(this.attach_PHIEUMUONs), new Action<PHIEUMUON>(this.detach_PHIEUMUONs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maDocGia", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int maDocGia
		{
			get
			{
				return this._maDocGia;
			}
			set
			{
				if ((this._maDocGia != value))
				{
					this.OnmaDocGiaChanging(value);
					this.SendPropertyChanging();
					this._maDocGia = value;
					this.SendPropertyChanged("maDocGia");
					this.OnmaDocGiaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_hoTenDG", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string hoTenDG
		{
			get
			{
				return this._hoTenDG;
			}
			set
			{
				if ((this._hoTenDG != value))
				{
					this.OnhoTenDGChanging(value);
					this.SendPropertyChanging();
					this._hoTenDG = value;
					this.SendPropertyChanged("hoTenDG");
					this.OnhoTenDGChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_gioiTinh", DbType="Bit")]
		public System.Nullable<bool> gioiTinh
		{
			get
			{
				return this._gioiTinh;
			}
			set
			{
				if ((this._gioiTinh != value))
				{
					this.OngioiTinhChanging(value);
					this.SendPropertyChanging();
					this._gioiTinh = value;
					this.SendPropertyChanged("gioiTinh");
					this.OngioiTinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ngaySinh", DbType="Date")]
		public System.Nullable<System.DateTime> ngaySinh
		{
			get
			{
				return this._ngaySinh;
			}
			set
			{
				if ((this._ngaySinh != value))
				{
					this.OnngaySinhChanging(value);
					this.SendPropertyChanging();
					this._ngaySinh = value;
					this.SendPropertyChanged("ngaySinh");
					this.OnngaySinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_diaChi", DbType="NVarChar(100)")]
		public string diaChi
		{
			get
			{
				return this._diaChi;
			}
			set
			{
				if ((this._diaChi != value))
				{
					this.OndiaChiChanging(value);
					this.SendPropertyChanging();
					this._diaChi = value;
					this.SendPropertyChanged("diaChi");
					this.OndiaChiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sdt", DbType="NChar(13)")]
		public string sdt
		{
			get
			{
				return this._sdt;
			}
			set
			{
				if ((this._sdt != value))
				{
					this.OnsdtChanging(value);
					this.SendPropertyChanging();
					this._sdt = value;
					this.SendPropertyChanged("sdt");
					this.OnsdtChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_email", DbType="NChar(50)")]
		public string email
		{
			get
			{
				return this._email;
			}
			set
			{
				if ((this._email != value))
				{
					this.OnemailChanging(value);
					this.SendPropertyChanging();
					this._email = value;
					this.SendPropertyChanged("email");
					this.OnemailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="DOCGIA_PHIEUMUON", Storage="_PHIEUMUONs", ThisKey="maDocGia", OtherKey="maDocGia")]
		public EntitySet<PHIEUMUON> PHIEUMUONs
		{
			get
			{
				return this._PHIEUMUONs;
			}
			set
			{
				this._PHIEUMUONs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_PHIEUMUONs(PHIEUMUON entity)
		{
			this.SendPropertyChanging();
			entity.DOCGIA = this;
		}
		
		private void detach_PHIEUMUONs(PHIEUMUON entity)
		{
			this.SendPropertyChanging();
			entity.DOCGIA = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.LOG_MUONTRA")]
	public partial class LOG_MUONTRA : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private string _hanhDong;
		
		private System.Nullable<int> _maSach;
		
		private System.Nullable<int> _maDocGia;
		
		private System.Nullable<int> _soLuong;
		
		private System.Nullable<System.DateTime> _thoiGianThucHien;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnhanhDongChanging(string value);
    partial void OnhanhDongChanged();
    partial void OnmaSachChanging(System.Nullable<int> value);
    partial void OnmaSachChanged();
    partial void OnmaDocGiaChanging(System.Nullable<int> value);
    partial void OnmaDocGiaChanged();
    partial void OnsoLuongChanging(System.Nullable<int> value);
    partial void OnsoLuongChanged();
    partial void OnthoiGianThucHienChanging(System.Nullable<System.DateTime> value);
    partial void OnthoiGianThucHienChanged();
    #endregion
		
		public LOG_MUONTRA()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_hanhDong", DbType="NVarChar(50)")]
		public string hanhDong
		{
			get
			{
				return this._hanhDong;
			}
			set
			{
				if ((this._hanhDong != value))
				{
					this.OnhanhDongChanging(value);
					this.SendPropertyChanging();
					this._hanhDong = value;
					this.SendPropertyChanged("hanhDong");
					this.OnhanhDongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maSach", DbType="Int")]
		public System.Nullable<int> maSach
		{
			get
			{
				return this._maSach;
			}
			set
			{
				if ((this._maSach != value))
				{
					this.OnmaSachChanging(value);
					this.SendPropertyChanging();
					this._maSach = value;
					this.SendPropertyChanged("maSach");
					this.OnmaSachChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maDocGia", DbType="Int")]
		public System.Nullable<int> maDocGia
		{
			get
			{
				return this._maDocGia;
			}
			set
			{
				if ((this._maDocGia != value))
				{
					this.OnmaDocGiaChanging(value);
					this.SendPropertyChanging();
					this._maDocGia = value;
					this.SendPropertyChanged("maDocGia");
					this.OnmaDocGiaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_soLuong", DbType="Int")]
		public System.Nullable<int> soLuong
		{
			get
			{
				return this._soLuong;
			}
			set
			{
				if ((this._soLuong != value))
				{
					this.OnsoLuongChanging(value);
					this.SendPropertyChanging();
					this._soLuong = value;
					this.SendPropertyChanged("soLuong");
					this.OnsoLuongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_thoiGianThucHien", DbType="DateTime")]
		public System.Nullable<System.DateTime> thoiGianThucHien
		{
			get
			{
				return this._thoiGianThucHien;
			}
			set
			{
				if ((this._thoiGianThucHien != value))
				{
					this.OnthoiGianThucHienChanging(value);
					this.SendPropertyChanging();
					this._thoiGianThucHien = value;
					this.SendPropertyChanged("thoiGianThucHien");
					this.OnthoiGianThucHienChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.NHANVIEN")]
	public partial class NHANVIEN : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _maNV;
		
		private string _hoTenNV;
		
		private System.Nullable<bool> _gioiTinh;
		
		private System.Nullable<System.DateTime> _ngaySinh;
		
		private string _chucVu;
		
		private string _sdt;
		
		private string _email;
		
		private string _DBUserName;
		
		private EntitySet<PHANCONG> _PHANCONGs;
		
		private EntitySet<PHIEUMUON> _PHIEUMUONs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnmaNVChanging(int value);
    partial void OnmaNVChanged();
    partial void OnhoTenNVChanging(string value);
    partial void OnhoTenNVChanged();
    partial void OngioiTinhChanging(System.Nullable<bool> value);
    partial void OngioiTinhChanged();
    partial void OnngaySinhChanging(System.Nullable<System.DateTime> value);
    partial void OnngaySinhChanged();
    partial void OnchucVuChanging(string value);
    partial void OnchucVuChanged();
    partial void OnsdtChanging(string value);
    partial void OnsdtChanged();
    partial void OnemailChanging(string value);
    partial void OnemailChanged();
    partial void OnDBUserNameChanging(string value);
    partial void OnDBUserNameChanged();
    #endregion
		
		public NHANVIEN()
		{
			this._PHANCONGs = new EntitySet<PHANCONG>(new Action<PHANCONG>(this.attach_PHANCONGs), new Action<PHANCONG>(this.detach_PHANCONGs));
			this._PHIEUMUONs = new EntitySet<PHIEUMUON>(new Action<PHIEUMUON>(this.attach_PHIEUMUONs), new Action<PHIEUMUON>(this.detach_PHIEUMUONs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maNV", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int maNV
		{
			get
			{
				return this._maNV;
			}
			set
			{
				if ((this._maNV != value))
				{
					this.OnmaNVChanging(value);
					this.SendPropertyChanging();
					this._maNV = value;
					this.SendPropertyChanged("maNV");
					this.OnmaNVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_hoTenNV", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string hoTenNV
		{
			get
			{
				return this._hoTenNV;
			}
			set
			{
				if ((this._hoTenNV != value))
				{
					this.OnhoTenNVChanging(value);
					this.SendPropertyChanging();
					this._hoTenNV = value;
					this.SendPropertyChanged("hoTenNV");
					this.OnhoTenNVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_gioiTinh", DbType="Bit")]
		public System.Nullable<bool> gioiTinh
		{
			get
			{
				return this._gioiTinh;
			}
			set
			{
				if ((this._gioiTinh != value))
				{
					this.OngioiTinhChanging(value);
					this.SendPropertyChanging();
					this._gioiTinh = value;
					this.SendPropertyChanged("gioiTinh");
					this.OngioiTinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ngaySinh", DbType="Date")]
		public System.Nullable<System.DateTime> ngaySinh
		{
			get
			{
				return this._ngaySinh;
			}
			set
			{
				if ((this._ngaySinh != value))
				{
					this.OnngaySinhChanging(value);
					this.SendPropertyChanging();
					this._ngaySinh = value;
					this.SendPropertyChanged("ngaySinh");
					this.OnngaySinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_chucVu", DbType="NVarChar(50)")]
		public string chucVu
		{
			get
			{
				return this._chucVu;
			}
			set
			{
				if ((this._chucVu != value))
				{
					this.OnchucVuChanging(value);
					this.SendPropertyChanging();
					this._chucVu = value;
					this.SendPropertyChanged("chucVu");
					this.OnchucVuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sdt", DbType="NChar(13)")]
		public string sdt
		{
			get
			{
				return this._sdt;
			}
			set
			{
				if ((this._sdt != value))
				{
					this.OnsdtChanging(value);
					this.SendPropertyChanging();
					this._sdt = value;
					this.SendPropertyChanged("sdt");
					this.OnsdtChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_email", DbType="NChar(50)")]
		public string email
		{
			get
			{
				return this._email;
			}
			set
			{
				if ((this._email != value))
				{
					this.OnemailChanging(value);
					this.SendPropertyChanging();
					this._email = value;
					this.SendPropertyChanged("email");
					this.OnemailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DBUserName", DbType="NVarChar(128)")]
		public string DBUserName
		{
			get
			{
				return this._DBUserName;
			}
			set
			{
				if ((this._DBUserName != value))
				{
					this.OnDBUserNameChanging(value);
					this.SendPropertyChanging();
					this._DBUserName = value;
					this.SendPropertyChanged("DBUserName");
					this.OnDBUserNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NHANVIEN_PHANCONG", Storage="_PHANCONGs", ThisKey="maNV", OtherKey="maNV")]
		public EntitySet<PHANCONG> PHANCONGs
		{
			get
			{
				return this._PHANCONGs;
			}
			set
			{
				this._PHANCONGs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NHANVIEN_PHIEUMUON", Storage="_PHIEUMUONs", ThisKey="maNV", OtherKey="maNV")]
		public EntitySet<PHIEUMUON> PHIEUMUONs
		{
			get
			{
				return this._PHIEUMUONs;
			}
			set
			{
				this._PHIEUMUONs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_PHANCONGs(PHANCONG entity)
		{
			this.SendPropertyChanging();
			entity.NHANVIEN = this;
		}
		
		private void detach_PHANCONGs(PHANCONG entity)
		{
			this.SendPropertyChanging();
			entity.NHANVIEN = null;
		}
		
		private void attach_PHIEUMUONs(PHIEUMUON entity)
		{
			this.SendPropertyChanging();
			entity.NHANVIEN = this;
		}
		
		private void detach_PHIEUMUONs(PHIEUMUON entity)
		{
			this.SendPropertyChanging();
			entity.NHANVIEN = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.NXB")]
	public partial class NXB : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _maNXB;
		
		private string _tenNXB;
		
		private string _diaChi;
		
		private EntitySet<SACH> _SACHes;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnmaNXBChanging(int value);
    partial void OnmaNXBChanged();
    partial void OntenNXBChanging(string value);
    partial void OntenNXBChanged();
    partial void OndiaChiChanging(string value);
    partial void OndiaChiChanged();
    #endregion
		
		public NXB()
		{
			this._SACHes = new EntitySet<SACH>(new Action<SACH>(this.attach_SACHes), new Action<SACH>(this.detach_SACHes));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maNXB", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int maNXB
		{
			get
			{
				return this._maNXB;
			}
			set
			{
				if ((this._maNXB != value))
				{
					this.OnmaNXBChanging(value);
					this.SendPropertyChanging();
					this._maNXB = value;
					this.SendPropertyChanged("maNXB");
					this.OnmaNXBChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tenNXB", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string tenNXB
		{
			get
			{
				return this._tenNXB;
			}
			set
			{
				if ((this._tenNXB != value))
				{
					this.OntenNXBChanging(value);
					this.SendPropertyChanging();
					this._tenNXB = value;
					this.SendPropertyChanged("tenNXB");
					this.OntenNXBChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_diaChi", DbType="NVarChar(100)")]
		public string diaChi
		{
			get
			{
				return this._diaChi;
			}
			set
			{
				if ((this._diaChi != value))
				{
					this.OndiaChiChanging(value);
					this.SendPropertyChanging();
					this._diaChi = value;
					this.SendPropertyChanged("diaChi");
					this.OndiaChiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NXB_SACH", Storage="_SACHes", ThisKey="maNXB", OtherKey="maNXB")]
		public EntitySet<SACH> SACHes
		{
			get
			{
				return this._SACHes;
			}
			set
			{
				this._SACHes.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_SACHes(SACH entity)
		{
			this.SendPropertyChanging();
			entity.NXB = this;
		}
		
		private void detach_SACHes(SACH entity)
		{
			this.SendPropertyChanging();
			entity.NXB = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.PHANCONG")]
	public partial class PHANCONG : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _maCA;
		
		private int _maNV;
		
		private System.DateTime _ngayPhanCong;
		
		private EntityRef<CALAMVIEC> _CALAMVIEC;
		
		private EntityRef<NHANVIEN> _NHANVIEN;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnmaCAChanging(int value);
    partial void OnmaCAChanged();
    partial void OnmaNVChanging(int value);
    partial void OnmaNVChanged();
    partial void OnngayPhanCongChanging(System.DateTime value);
    partial void OnngayPhanCongChanged();
    #endregion
		
		public PHANCONG()
		{
			this._CALAMVIEC = default(EntityRef<CALAMVIEC>);
			this._NHANVIEN = default(EntityRef<NHANVIEN>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maCA", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int maCA
		{
			get
			{
				return this._maCA;
			}
			set
			{
				if ((this._maCA != value))
				{
					if (this._CALAMVIEC.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnmaCAChanging(value);
					this.SendPropertyChanging();
					this._maCA = value;
					this.SendPropertyChanged("maCA");
					this.OnmaCAChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maNV", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int maNV
		{
			get
			{
				return this._maNV;
			}
			set
			{
				if ((this._maNV != value))
				{
					if (this._NHANVIEN.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnmaNVChanging(value);
					this.SendPropertyChanging();
					this._maNV = value;
					this.SendPropertyChanged("maNV");
					this.OnmaNVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ngayPhanCong", DbType="Date NOT NULL", IsPrimaryKey=true)]
		public System.DateTime ngayPhanCong
		{
			get
			{
				return this._ngayPhanCong;
			}
			set
			{
				if ((this._ngayPhanCong != value))
				{
					this.OnngayPhanCongChanging(value);
					this.SendPropertyChanging();
					this._ngayPhanCong = value;
					this.SendPropertyChanged("ngayPhanCong");
					this.OnngayPhanCongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="CALAMVIEC_PHANCONG", Storage="_CALAMVIEC", ThisKey="maCA", OtherKey="maCA", IsForeignKey=true)]
		public CALAMVIEC CALAMVIEC
		{
			get
			{
				return this._CALAMVIEC.Entity;
			}
			set
			{
				CALAMVIEC previousValue = this._CALAMVIEC.Entity;
				if (((previousValue != value) 
							|| (this._CALAMVIEC.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._CALAMVIEC.Entity = null;
						previousValue.PHANCONGs.Remove(this);
					}
					this._CALAMVIEC.Entity = value;
					if ((value != null))
					{
						value.PHANCONGs.Add(this);
						this._maCA = value.maCA;
					}
					else
					{
						this._maCA = default(int);
					}
					this.SendPropertyChanged("CALAMVIEC");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NHANVIEN_PHANCONG", Storage="_NHANVIEN", ThisKey="maNV", OtherKey="maNV", IsForeignKey=true)]
		public NHANVIEN NHANVIEN
		{
			get
			{
				return this._NHANVIEN.Entity;
			}
			set
			{
				NHANVIEN previousValue = this._NHANVIEN.Entity;
				if (((previousValue != value) 
							|| (this._NHANVIEN.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._NHANVIEN.Entity = null;
						previousValue.PHANCONGs.Remove(this);
					}
					this._NHANVIEN.Entity = value;
					if ((value != null))
					{
						value.PHANCONGs.Add(this);
						this._maNV = value.maNV;
					}
					else
					{
						this._maNV = default(int);
					}
					this.SendPropertyChanged("NHANVIEN");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.PHIEUMUON")]
	public partial class PHIEUMUON : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _maPMUON;
		
		private System.Nullable<System.DateTime> _ngayMuon;
		
		private System.Nullable<System.DateTime> _ngayTra;
		
		private System.Nullable<bool> _daTra;
		
		private System.Nullable<int> _maDocGia;
		
		private System.Nullable<int> _maNV;
		
		private EntitySet<CTPHIEUMUON> _CTPHIEUMUONs;
		
		private EntityRef<DOCGIA> _DOCGIA;
		
		private EntityRef<NHANVIEN> _NHANVIEN;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnmaPMUONChanging(int value);
    partial void OnmaPMUONChanged();
    partial void OnngayMuonChanging(System.Nullable<System.DateTime> value);
    partial void OnngayMuonChanged();
    partial void OnngayTraChanging(System.Nullable<System.DateTime> value);
    partial void OnngayTraChanged();
    partial void OndaTraChanging(System.Nullable<bool> value);
    partial void OndaTraChanged();
    partial void OnmaDocGiaChanging(System.Nullable<int> value);
    partial void OnmaDocGiaChanged();
    partial void OnmaNVChanging(System.Nullable<int> value);
    partial void OnmaNVChanged();
    #endregion
		
		public PHIEUMUON()
		{
			this._CTPHIEUMUONs = new EntitySet<CTPHIEUMUON>(new Action<CTPHIEUMUON>(this.attach_CTPHIEUMUONs), new Action<CTPHIEUMUON>(this.detach_CTPHIEUMUONs));
			this._DOCGIA = default(EntityRef<DOCGIA>);
			this._NHANVIEN = default(EntityRef<NHANVIEN>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maPMUON", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int maPMUON
		{
			get
			{
				return this._maPMUON;
			}
			set
			{
				if ((this._maPMUON != value))
				{
					this.OnmaPMUONChanging(value);
					this.SendPropertyChanging();
					this._maPMUON = value;
					this.SendPropertyChanged("maPMUON");
					this.OnmaPMUONChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ngayMuon", DbType="Date")]
		public System.Nullable<System.DateTime> ngayMuon
		{
			get
			{
				return this._ngayMuon;
			}
			set
			{
				if ((this._ngayMuon != value))
				{
					this.OnngayMuonChanging(value);
					this.SendPropertyChanging();
					this._ngayMuon = value;
					this.SendPropertyChanged("ngayMuon");
					this.OnngayMuonChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ngayTra", DbType="Date")]
		public System.Nullable<System.DateTime> ngayTra
		{
			get
			{
				return this._ngayTra;
			}
			set
			{
				if ((this._ngayTra != value))
				{
					this.OnngayTraChanging(value);
					this.SendPropertyChanging();
					this._ngayTra = value;
					this.SendPropertyChanged("ngayTra");
					this.OnngayTraChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_daTra", DbType="Bit")]
		public System.Nullable<bool> daTra
		{
			get
			{
				return this._daTra;
			}
			set
			{
				if ((this._daTra != value))
				{
					this.OndaTraChanging(value);
					this.SendPropertyChanging();
					this._daTra = value;
					this.SendPropertyChanged("daTra");
					this.OndaTraChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maDocGia", DbType="Int")]
		public System.Nullable<int> maDocGia
		{
			get
			{
				return this._maDocGia;
			}
			set
			{
				if ((this._maDocGia != value))
				{
					if (this._DOCGIA.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnmaDocGiaChanging(value);
					this.SendPropertyChanging();
					this._maDocGia = value;
					this.SendPropertyChanged("maDocGia");
					this.OnmaDocGiaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maNV", DbType="Int")]
		public System.Nullable<int> maNV
		{
			get
			{
				return this._maNV;
			}
			set
			{
				if ((this._maNV != value))
				{
					if (this._NHANVIEN.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnmaNVChanging(value);
					this.SendPropertyChanging();
					this._maNV = value;
					this.SendPropertyChanged("maNV");
					this.OnmaNVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="PHIEUMUON_CTPHIEUMUON", Storage="_CTPHIEUMUONs", ThisKey="maPMUON", OtherKey="maPMUON")]
		public EntitySet<CTPHIEUMUON> CTPHIEUMUONs
		{
			get
			{
				return this._CTPHIEUMUONs;
			}
			set
			{
				this._CTPHIEUMUONs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="DOCGIA_PHIEUMUON", Storage="_DOCGIA", ThisKey="maDocGia", OtherKey="maDocGia", IsForeignKey=true)]
		public DOCGIA DOCGIA
		{
			get
			{
				return this._DOCGIA.Entity;
			}
			set
			{
				DOCGIA previousValue = this._DOCGIA.Entity;
				if (((previousValue != value) 
							|| (this._DOCGIA.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._DOCGIA.Entity = null;
						previousValue.PHIEUMUONs.Remove(this);
					}
					this._DOCGIA.Entity = value;
					if ((value != null))
					{
						value.PHIEUMUONs.Add(this);
						this._maDocGia = value.maDocGia;
					}
					else
					{
						this._maDocGia = default(Nullable<int>);
					}
					this.SendPropertyChanged("DOCGIA");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NHANVIEN_PHIEUMUON", Storage="_NHANVIEN", ThisKey="maNV", OtherKey="maNV", IsForeignKey=true)]
		public NHANVIEN NHANVIEN
		{
			get
			{
				return this._NHANVIEN.Entity;
			}
			set
			{
				NHANVIEN previousValue = this._NHANVIEN.Entity;
				if (((previousValue != value) 
							|| (this._NHANVIEN.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._NHANVIEN.Entity = null;
						previousValue.PHIEUMUONs.Remove(this);
					}
					this._NHANVIEN.Entity = value;
					if ((value != null))
					{
						value.PHIEUMUONs.Add(this);
						this._maNV = value.maNV;
					}
					else
					{
						this._maNV = default(Nullable<int>);
					}
					this.SendPropertyChanged("NHANVIEN");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_CTPHIEUMUONs(CTPHIEUMUON entity)
		{
			this.SendPropertyChanging();
			entity.PHIEUMUON = this;
		}
		
		private void detach_CTPHIEUMUONs(CTPHIEUMUON entity)
		{
			this.SendPropertyChanging();
			entity.PHIEUMUON = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.SACH")]
	public partial class SACH : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _maSach;
		
		private string _tenSach;
		
		private System.Nullable<int> _namXuatBan;
		
		private System.Nullable<int> _slSach;
		
		private System.Nullable<int> _SlConLai;
		
		private System.Nullable<int> _maNXB;
		
		private System.Nullable<int> _maTL;
		
		private System.Nullable<int> _maTG;
		
		private string _anhBia;
		
		private string _mota;
		
		private EntitySet<CTPHIEUMUON> _CTPHIEUMUONs;
		
		private EntityRef<NXB> _NXB;
		
		private EntityRef<THELOAI> _THELOAI;
		
		private EntityRef<TACGIA> _TACGIA;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnmaSachChanging(int value);
    partial void OnmaSachChanged();
    partial void OntenSachChanging(string value);
    partial void OntenSachChanged();
    partial void OnnamXuatBanChanging(System.Nullable<int> value);
    partial void OnnamXuatBanChanged();
    partial void OnslSachChanging(System.Nullable<int> value);
    partial void OnslSachChanged();
    partial void OnSlConLaiChanging(System.Nullable<int> value);
    partial void OnSlConLaiChanged();
    partial void OnmaNXBChanging(System.Nullable<int> value);
    partial void OnmaNXBChanged();
    partial void OnmaTLChanging(System.Nullable<int> value);
    partial void OnmaTLChanged();
    partial void OnmaTGChanging(System.Nullable<int> value);
    partial void OnmaTGChanged();
    partial void OnanhBiaChanging(string value);
    partial void OnanhBiaChanged();
    partial void OnmotaChanging(string value);
    partial void OnmotaChanged();
    #endregion
		
		public SACH()
		{
			this._CTPHIEUMUONs = new EntitySet<CTPHIEUMUON>(new Action<CTPHIEUMUON>(this.attach_CTPHIEUMUONs), new Action<CTPHIEUMUON>(this.detach_CTPHIEUMUONs));
			this._NXB = default(EntityRef<NXB>);
			this._THELOAI = default(EntityRef<THELOAI>);
			this._TACGIA = default(EntityRef<TACGIA>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maSach", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int maSach
		{
			get
			{
				return this._maSach;
			}
			set
			{
				if ((this._maSach != value))
				{
					this.OnmaSachChanging(value);
					this.SendPropertyChanging();
					this._maSach = value;
					this.SendPropertyChanged("maSach");
					this.OnmaSachChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tenSach", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string tenSach
		{
			get
			{
				return this._tenSach;
			}
			set
			{
				if ((this._tenSach != value))
				{
					this.OntenSachChanging(value);
					this.SendPropertyChanging();
					this._tenSach = value;
					this.SendPropertyChanged("tenSach");
					this.OntenSachChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_namXuatBan", DbType="Int")]
		public System.Nullable<int> namXuatBan
		{
			get
			{
				return this._namXuatBan;
			}
			set
			{
				if ((this._namXuatBan != value))
				{
					this.OnnamXuatBanChanging(value);
					this.SendPropertyChanging();
					this._namXuatBan = value;
					this.SendPropertyChanged("namXuatBan");
					this.OnnamXuatBanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_slSach", DbType="Int")]
		public System.Nullable<int> slSach
		{
			get
			{
				return this._slSach;
			}
			set
			{
				if ((this._slSach != value))
				{
					this.OnslSachChanging(value);
					this.SendPropertyChanging();
					this._slSach = value;
					this.SendPropertyChanged("slSach");
					this.OnslSachChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SlConLai", DbType="Int")]
		public System.Nullable<int> SlConLai
		{
			get
			{
				return this._SlConLai;
			}
			set
			{
				if ((this._SlConLai != value))
				{
					this.OnSlConLaiChanging(value);
					this.SendPropertyChanging();
					this._SlConLai = value;
					this.SendPropertyChanged("SlConLai");
					this.OnSlConLaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maNXB", DbType="Int")]
		public System.Nullable<int> maNXB
		{
			get
			{
				return this._maNXB;
			}
			set
			{
				if ((this._maNXB != value))
				{
					if (this._NXB.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnmaNXBChanging(value);
					this.SendPropertyChanging();
					this._maNXB = value;
					this.SendPropertyChanged("maNXB");
					this.OnmaNXBChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maTL", DbType="Int")]
		public System.Nullable<int> maTL
		{
			get
			{
				return this._maTL;
			}
			set
			{
				if ((this._maTL != value))
				{
					if (this._THELOAI.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnmaTLChanging(value);
					this.SendPropertyChanging();
					this._maTL = value;
					this.SendPropertyChanged("maTL");
					this.OnmaTLChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maTG", DbType="Int")]
		public System.Nullable<int> maTG
		{
			get
			{
				return this._maTG;
			}
			set
			{
				if ((this._maTG != value))
				{
					if (this._TACGIA.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnmaTGChanging(value);
					this.SendPropertyChanging();
					this._maTG = value;
					this.SendPropertyChanged("maTG");
					this.OnmaTGChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_anhBia", DbType="NVarChar(200)")]
		public string anhBia
		{
			get
			{
				return this._anhBia;
			}
			set
			{
				if ((this._anhBia != value))
				{
					this.OnanhBiaChanging(value);
					this.SendPropertyChanging();
					this._anhBia = value;
					this.SendPropertyChanged("anhBia");
					this.OnanhBiaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_mota", DbType="NVarChar(MAX)")]
		public string mota
		{
			get
			{
				return this._mota;
			}
			set
			{
				if ((this._mota != value))
				{
					this.OnmotaChanging(value);
					this.SendPropertyChanging();
					this._mota = value;
					this.SendPropertyChanged("mota");
					this.OnmotaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="SACH_CTPHIEUMUON", Storage="_CTPHIEUMUONs", ThisKey="maSach", OtherKey="maSach")]
		public EntitySet<CTPHIEUMUON> CTPHIEUMUONs
		{
			get
			{
				return this._CTPHIEUMUONs;
			}
			set
			{
				this._CTPHIEUMUONs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NXB_SACH", Storage="_NXB", ThisKey="maNXB", OtherKey="maNXB", IsForeignKey=true)]
		public NXB NXB
		{
			get
			{
				return this._NXB.Entity;
			}
			set
			{
				NXB previousValue = this._NXB.Entity;
				if (((previousValue != value) 
							|| (this._NXB.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._NXB.Entity = null;
						previousValue.SACHes.Remove(this);
					}
					this._NXB.Entity = value;
					if ((value != null))
					{
						value.SACHes.Add(this);
						this._maNXB = value.maNXB;
					}
					else
					{
						this._maNXB = default(Nullable<int>);
					}
					this.SendPropertyChanged("NXB");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="THELOAI_SACH", Storage="_THELOAI", ThisKey="maTL", OtherKey="maTL", IsForeignKey=true)]
		public THELOAI THELOAI
		{
			get
			{
				return this._THELOAI.Entity;
			}
			set
			{
				THELOAI previousValue = this._THELOAI.Entity;
				if (((previousValue != value) 
							|| (this._THELOAI.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._THELOAI.Entity = null;
						previousValue.SACHes.Remove(this);
					}
					this._THELOAI.Entity = value;
					if ((value != null))
					{
						value.SACHes.Add(this);
						this._maTL = value.maTL;
					}
					else
					{
						this._maTL = default(Nullable<int>);
					}
					this.SendPropertyChanged("THELOAI");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TACGIA_SACH", Storage="_TACGIA", ThisKey="maTG", OtherKey="maTG", IsForeignKey=true)]
		public TACGIA TACGIA
		{
			get
			{
				return this._TACGIA.Entity;
			}
			set
			{
				TACGIA previousValue = this._TACGIA.Entity;
				if (((previousValue != value) 
							|| (this._TACGIA.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._TACGIA.Entity = null;
						previousValue.SACHes.Remove(this);
					}
					this._TACGIA.Entity = value;
					if ((value != null))
					{
						value.SACHes.Add(this);
						this._maTG = value.maTG;
					}
					else
					{
						this._maTG = default(Nullable<int>);
					}
					this.SendPropertyChanged("TACGIA");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_CTPHIEUMUONs(CTPHIEUMUON entity)
		{
			this.SendPropertyChanging();
			entity.SACH = this;
		}
		
		private void detach_CTPHIEUMUONs(CTPHIEUMUON entity)
		{
			this.SendPropertyChanging();
			entity.SACH = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TACGIA")]
	public partial class TACGIA : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _maTG;
		
		private string _hoTenTG;
		
		private System.Nullable<System.DateTime> _ngaySinh;
		
		private System.Nullable<bool> _gioiTinh;
		
		private EntitySet<SACH> _SACHes;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnmaTGChanging(int value);
    partial void OnmaTGChanged();
    partial void OnhoTenTGChanging(string value);
    partial void OnhoTenTGChanged();
    partial void OnngaySinhChanging(System.Nullable<System.DateTime> value);
    partial void OnngaySinhChanged();
    partial void OngioiTinhChanging(System.Nullable<bool> value);
    partial void OngioiTinhChanged();
    #endregion
		
		public TACGIA()
		{
			this._SACHes = new EntitySet<SACH>(new Action<SACH>(this.attach_SACHes), new Action<SACH>(this.detach_SACHes));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maTG", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int maTG
		{
			get
			{
				return this._maTG;
			}
			set
			{
				if ((this._maTG != value))
				{
					this.OnmaTGChanging(value);
					this.SendPropertyChanging();
					this._maTG = value;
					this.SendPropertyChanged("maTG");
					this.OnmaTGChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_hoTenTG", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string hoTenTG
		{
			get
			{
				return this._hoTenTG;
			}
			set
			{
				if ((this._hoTenTG != value))
				{
					this.OnhoTenTGChanging(value);
					this.SendPropertyChanging();
					this._hoTenTG = value;
					this.SendPropertyChanged("hoTenTG");
					this.OnhoTenTGChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ngaySinh", DbType="Date")]
		public System.Nullable<System.DateTime> ngaySinh
		{
			get
			{
				return this._ngaySinh;
			}
			set
			{
				if ((this._ngaySinh != value))
				{
					this.OnngaySinhChanging(value);
					this.SendPropertyChanging();
					this._ngaySinh = value;
					this.SendPropertyChanged("ngaySinh");
					this.OnngaySinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_gioiTinh", DbType="Bit")]
		public System.Nullable<bool> gioiTinh
		{
			get
			{
				return this._gioiTinh;
			}
			set
			{
				if ((this._gioiTinh != value))
				{
					this.OngioiTinhChanging(value);
					this.SendPropertyChanging();
					this._gioiTinh = value;
					this.SendPropertyChanged("gioiTinh");
					this.OngioiTinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TACGIA_SACH", Storage="_SACHes", ThisKey="maTG", OtherKey="maTG")]
		public EntitySet<SACH> SACHes
		{
			get
			{
				return this._SACHes;
			}
			set
			{
				this._SACHes.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_SACHes(SACH entity)
		{
			this.SendPropertyChanging();
			entity.TACGIA = this;
		}
		
		private void detach_SACHes(SACH entity)
		{
			this.SendPropertyChanging();
			entity.TACGIA = null;
		}
	}
}
#pragma warning restore 1591
